### ISSUE TITLE
What was the purpose of this language?

### ISSUE THREAD

**Issue by antonpichka** [egormanga/Slang#1]
Why was it necessary to create this language? What problem does it solve? If, for example, Dart was created to replace JavaScript, and the reason was, Mark Miller's quote: "JavaScript 'has fundamental flaws' that cannot be fixed." That's why Dart was created.
Maybe with the help of this language it will be possible to create a new concept that will be better than OOP? or modify? and then the code will become more readable and applications will be created faster?
I'm interested to hear your answer :). And I'm not trying to offend you in any way.

**Comment by egormanga** [comment]
I could've written a really comprehensive answer to that, but for the current (pretty early) state of development, it's sufficient to refer back to the initial motivation: to create a frontend for SBC, which is a bytecode aimed to juice my other project, [Sos](https://apps.sdore.me/egormanga/Sos) — a next-gen desktop operating system, that has been in private development for over 3 years as of today.

Thank you for your interest! I'm glad that the project is at least minimally capable of finding its own community over time.

Unless you still do have any questions that are more specific, please close the issue. I might reopen it when the time comes to evaluate the aforementioned alternative concepts and/or reassess the overall future of the project(-s).
